"""
KEGG pathway 静态映射查表|KEGG pathway static map lookup.

加载内置 kegg_data.py(由 scripts/build_kegg_pathway_map.py 生成), 提供
ko_id -> (name, category) 查询. 纯离线, 计算节点无网可用.
|Load built-in kegg_data.py (generated by build_kegg_pathway_map.py), provide
ko_id -> (name, category) lookup. Fully offline; works on compute nodes.

category 为可选字段, 超算生成的 kegg_data.py 可能全空(需本地补 BRITE).
|category is optional; on HPC kegg_data.py may have empty category (fill locally).
"""

import logging
from pathlib import Path
from threading import Lock
from typing import Dict, Optional

from .kegg_data import KEGG_PATHWAY


class KEGGDatabase:
    """KEGG pathway 查表(单例)|KEGG pathway lookup (singleton)."""

    _instance = None
    _lock = Lock()

    def __new__(cls, *args, **kwargs):
        """单例模式|Singleton pattern."""
        if cls._instance is None:
            with cls._lock:
                if cls._instance is None:
                    cls._instance = super().__new__(cls)
        return cls._instance

    def __init__(self, kegg_map_file: Optional[str] = None,
                 logger: Optional[logging.Logger] = None):
        """
        初始化|Initialize.

        Args:
            kegg_map_file: 可选外部映射 TSV(ko_id\\tname[\\tcategory]), 覆盖/补全内置.
                           |Optional external TSV (ko_id\\tname[\\tcategory]) to override/supplement.
            logger: 日志器|Logger.
        """
        if hasattr(self, "_initialized") and self._initialized:
            # 已初始化过, 仅可选地补入外部映射|already init; optionally merge external
            if kegg_map_file:
                self._load_external(kegg_map_file)
            return

        self.logger = logger or logging.getLogger(__name__)
        self.pathway_map: Dict[str, Dict[str, str]] = {}

        # 加载内置 kegg_data.py|load built-in
        for kid, val in KEGG_PATHWAY.items():
            name, cat = self._normalize(val)
            self.pathway_map[kid] = {"name": name, "category": cat}

        total = len(self.pathway_map)
        with_cat = sum(1 for v in self.pathway_map.values() if v["category"])
        self.logger.info(
            f"内置 KEGG 映射加载|Loaded KEGG map: {total} 条|entries "
            f"(category 命中|with category: {with_cat})"
        )

        if kegg_map_file:
            self._load_external(kegg_map_file)

        self._initialized = True

    @staticmethod
    def _normalize(val) -> tuple:
        """归一化 kegg_data 的值 → (name, category)|Normalize value → (name, category)."""
        if isinstance(val, (tuple, list)):
            name = val[0] if val else ""
            cat = val[1] if len(val) > 1 else ""
            return str(name), str(cat)
        # 旧格式: 纯字符串 name|legacy: bare string name
        return str(val), ""

    def _load_external(self, path: str):
        """加载外部 TSV 覆盖/补全|Load external TSV to override/supplement.

        格式|Format: ko_id \\t name [\\t category]  (可带或不带 # 注释头)
        """
        p = Path(path)
        if not p.exists():
            self.logger.warning(f"外部 KEGG 映射不存在|External KEGG map not found: {path}")
            return
        n = 0
        with open(p, encoding="utf-8") as f:
            for line in f:
                line = line.rstrip("\n")
                if not line or line.startswith("#"):
                    continue
                parts = line.split("\t")
                if len(parts) < 2:
                    continue
                kid = parts[0].strip()
                name = parts[1].strip()
                cat = parts[2].strip() if len(parts) > 2 else ""
                existing = self.pathway_map.get(kid, {"name": "", "category": ""})
                # 非空才覆盖, 避免空值冲掉已有|only override with non-empty
                if name:
                    existing["name"] = name
                if cat:
                    existing["category"] = cat
                self.pathway_map[kid] = existing
                n += 1
        self.logger.info(f"外部 KEGG 映射合并|Merged external KEGG map: {n} 条|entries ({path})")

    def get_pathway_info(self, ko_id: str) -> Dict[str, str]:
        """
        查 pathway 信息|Look up pathway info.

        Args:
            ko_id: pathway id, 如 "ko04110"(eggnog 原生 ko 前缀)|pathway id, e.g. "ko04110".

        Returns:
            {"name": ..., "category": ...}, 未命中返回空串|dict; empty strings if miss.
        """
        kid = (ko_id or "").strip()
        if not kid or kid == "-":
            return {"name": "", "category": ""}
        # 规范化: 无 ko 前缀且为纯 pathway 编号则补前缀|normalize prefix
        if not kid.startswith("ko") and kid[:5].isdigit():
            kid = "ko" + kid
        return self.pathway_map.get(kid, {"name": "", "category": ""})

    def get_name(self, ko_id: str) -> str:
        """获取 pathway 描述|Get pathway description."""
        return self.get_pathway_info(ko_id).get("name", "")

    def get_category(self, ko_id: str) -> str:
        """获取 pathway A 级分类|Get pathway A-level category."""
        return self.get_pathway_info(ko_id).get("category", "")
