zcat /share/org/YZWL/yzwl_lixg/project/16.荠菜/01.data/clean/51_1.clean.fq.gz >> /share/org/YZWL/yzwl_lixg/project/16.荠菜/15.each_8_samples/S_1.fq
zcat /share/org/YZWL/yzwl_lixg/project/16.荠菜/01.data/clean/51_2.clean.fq.gz >> /share/org/YZWL/yzwl_lixg/project/16.荠菜/15.each_8_samples/S_2.fq
zcat /share/org/YZWL/yzwl_lixg/project/16.荠菜/01.data/clean/78_1.clean.fq.gz >> /share/org/YZWL/yzwl_lixg/project/16.荠菜/15.each_8_samples/R_1.fq
zcat /share/org/YZWL/yzwl_lixg/project/16.荠菜/01.data/clean/78_2.clean.fq.gz >> /share/org/YZWL/yzwl_lixg/project/16.荠菜/15.each_8_samples/R_2.fq
zcat /share/org/YZWL/yzwl_lixg/project/16.荠菜/01.data/clean/28_1.clean.fq.gz >> /share/org/YZWL/yzwl_lixg/project/16.荠菜/15.each_8_samples/S_1.fq
zcat /share/org/YZWL/yzwl_lixg/project/16.荠菜/01.data/clean/28_2.clean.fq.gz >> /share/org/YZWL/yzwl_lixg/project/16.荠菜/15.each_8_samples/S_2.fq
zcat /share/org/YZWL/yzwl_lixg/project/16.荠菜/01.data/clean/88_1.clean.fq.gz >> /share/org/YZWL/yzwl_lixg/project/16.荠菜/15.each_8_samples/R_1.fq
zcat /share/org/YZWL/yzwl_lixg/project/16.荠菜/01.data/clean/88_2.clean.fq.gz >> /share/org/YZWL/yzwl_lixg/project/16.荠菜/15.each_8_samples/R_2.fq
zcat /share/org/YZWL/yzwl_lixg/project/16.荠菜/01.data/clean/41_1.clean.fq.gz >> /share/org/YZWL/yzwl_lixg/project/16.荠菜/15.each_8_samples/S_1.fq
zcat /share/org/YZWL/yzwl_lixg/project/16.荠菜/01.data/clean/41_2.clean.fq.gz >> /share/org/YZWL/yzwl_lixg/project/16.荠菜/15.each_8_samples/S_2.fq
zcat /share/org/YZWL/yzwl_lixg/project/16.荠菜/01.data/clean/85_1.clean.fq.gz >> /share/org/YZWL/yzwl_lixg/project/16.荠菜/15.each_8_samples/R_1.fq
zcat /share/org/YZWL/yzwl_lixg/project/16.荠菜/01.data/clean/85_2.clean.fq.gz >> /share/org/YZWL/yzwl_lixg/project/16.荠菜/15.each_8_samples/R_2.fq
zcat /share/org/YZWL/yzwl_lixg/project/16.荠菜/01.data/clean/54_1.clean.fq.gz >> /share/org/YZWL/yzwl_lixg/project/16.荠菜/15.each_8_samples/S_1.fq
zcat /share/org/YZWL/yzwl_lixg/project/16.荠菜/01.data/clean/54_2.clean.fq.gz >> /share/org/YZWL/yzwl_lixg/project/16.荠菜/15.each_8_samples/S_2.fq
zcat /share/org/YZWL/yzwl_lixg/project/16.荠菜/01.data/clean/89_1.clean.fq.gz >> /share/org/YZWL/yzwl_lixg/project/16.荠菜/15.each_8_samples/R_1.fq
zcat /share/org/YZWL/yzwl_lixg/project/16.荠菜/01.data/clean/89_2.clean.fq.gz >> /share/org/YZWL/yzwl_lixg/project/16.荠菜/15.each_8_samples/R_2.fq
zcat /share/org/YZWL/yzwl_lixg/project/16.荠菜/01.data/clean/48_1.clean.fq.gz >> /share/org/YZWL/yzwl_lixg/project/16.荠菜/15.each_8_samples/S_1.fq
zcat /share/org/YZWL/yzwl_lixg/project/16.荠菜/01.data/clean/48_2.clean.fq.gz >> /share/org/YZWL/yzwl_lixg/project/16.荠菜/15.each_8_samples/S_2.fq
zcat /share/org/YZWL/yzwl_lixg/project/16.荠菜/01.data/clean/59_1.clean.fq.gz >> /share/org/YZWL/yzwl_lixg/project/16.荠菜/15.each_8_samples/R_1.fq
zcat /share/org/YZWL/yzwl_lixg/project/16.荠菜/01.data/clean/59_2.clean.fq.gz >> /share/org/YZWL/yzwl_lixg/project/16.荠菜/15.each_8_samples/R_2.fq
zcat /share/org/YZWL/yzwl_lixg/project/16.荠菜/01.data/clean/49_1.clean.fq.gz >> /share/org/YZWL/yzwl_lixg/project/16.荠菜/15.each_8_samples/S_1.fq
zcat /share/org/YZWL/yzwl_lixg/project/16.荠菜/01.data/clean/49_2.clean.fq.gz >> /share/org/YZWL/yzwl_lixg/project/16.荠菜/15.each_8_samples/S_2.fq
zcat /share/org/YZWL/yzwl_lixg/project/16.荠菜/01.data/clean/69_1.clean.fq.gz >> /share/org/YZWL/yzwl_lixg/project/16.荠菜/15.each_8_samples/R_1.fq
zcat /share/org/YZWL/yzwl_lixg/project/16.荠菜/01.data/clean/69_2.clean.fq.gz >> /share/org/YZWL/yzwl_lixg/project/16.荠菜/15.each_8_samples/R_2.fq
zcat /share/org/YZWL/yzwl_lixg/project/16.荠菜/01.data/clean/40_1.clean.fq.gz >> /share/org/YZWL/yzwl_lixg/project/16.荠菜/15.each_8_samples/S_1.fq
zcat /share/org/YZWL/yzwl_lixg/project/16.荠菜/01.data/clean/40_2.clean.fq.gz >> /share/org/YZWL/yzwl_lixg/project/16.荠菜/15.each_8_samples/S_2.fq
zcat /share/org/YZWL/yzwl_lixg/project/16.荠菜/01.data/clean/105_1.clean.fq.gz >> /share/org/YZWL/yzwl_lixg/project/16.荠菜/15.each_8_samples/R_1.fq
zcat /share/org/YZWL/yzwl_lixg/project/16.荠菜/01.data/clean/105_2.clean.fq.gz >> /share/org/YZWL/yzwl_lixg/project/16.荠菜/15.each_8_samples/R_2.fq
zcat /share/org/YZWL/yzwl_lixg/project/16.荠菜/01.data/clean/45_1.clean.fq.gz >> /share/org/YZWL/yzwl_lixg/project/16.荠菜/15.each_8_samples/S_1.fq
zcat /share/org/YZWL/yzwl_lixg/project/16.荠菜/01.data/clean/45_2.clean.fq.gz >> /share/org/YZWL/yzwl_lixg/project/16.荠菜/15.each_8_samples/S_2.fq
zcat /share/org/YZWL/yzwl_lixg/project/16.荠菜/01.data/clean/57_1.clean.fq.gz >> /share/org/YZWL/yzwl_lixg/project/16.荠菜/15.each_8_samples/R_1.fq
zcat /share/org/YZWL/yzwl_lixg/project/16.荠菜/01.data/clean/57_2.clean.fq.gz >> /share/org/YZWL/yzwl_lixg/project/16.荠菜/15.each_8_samples/R_2.fq
