cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/N10-14.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/A3-17.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/A3-57.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/A3-18.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/B3-2.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/N8-7.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/B2-2.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/N2-8.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/N3-5.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/B2-1.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/N6-1.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/N8-5.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/N3-6.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/N8-4.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/M-16.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/B4-18.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/B3-16.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/N2-1.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/A1-10.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/A3-2.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/D2-8.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/D4-9.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/D2-12.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/SRR10321576.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/A1-17.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/D2-11.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/K1-2.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/N11-6.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/B4-5.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/N4-1.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/D3-3.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/M-6.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/SRR7532837.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/A1-8.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/N10-4.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/SRR7532827.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/SRR7532838.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/6497.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/P6497.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/SRR7532823.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/SRR7532844.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/SRR7532826.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/SRR7532831.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/SRR7532821.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/SRR7532829.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/SRR10321555.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/SRR7532842.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/SRR7532841.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/SRR7532828.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/SRR7532847.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/SRR7532849.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/SRR7532851.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/SRR7532843.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/SRR7532822.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/SRR7532845.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/SRR1046800.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/7076.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/SRR12021955.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/SRR7532830.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/SRR10321574.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/SRR7532835.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/N2-6.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/D4-5.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/D2-1.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/B4-1.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/N12-2.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/D2-16.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/D2-5.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/D4-1.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/M-7.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/N10-9.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/M-9.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/M-11.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/M-4.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/B4-22.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/A1-18.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/N12-6.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/N3-2.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/N3-9.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/N3-3.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/N8-6.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/B3-5.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/N4-2.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/D1-1.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/41.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/N2-9.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/D6-8.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/N12-5.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/N8-9.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/A1-2.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/A1-1.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/M-13.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/N8-10.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/A1-3.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/M-8.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/SRR10321572.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/D3-2.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/N10-10.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/N11-7.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/N11-1.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/A2-3.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/N2-11.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/B4-10.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/B4-50.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/K2-23.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/N10-16.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/N10-8.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/D2-4.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/B3-15.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/N8-8.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/A2-5.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/A3-16.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/D5-2.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/A2-1.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/N10-3.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/SRR10321571.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/SRR10321552.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/SRR10321563.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/SRR10321559.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/SRR10321560.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/T30-4.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/Nov-9.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/SRR22980487.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/SRR22980484.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/SRR22980490.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/SRR22980483.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/SRR22980488.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/SRR10321558.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/SG30.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/D1-5.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/D4-2.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/A3-54.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/B3-8.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/A3-48.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/B3-12.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/A3-4.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/A3-22.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/A3-14.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/N3-16.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/D6-3.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/M-12.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/K2-9.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
cp /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/02.mapping/vcf/K2-16.g.vcf.gz /share/org/YZWL/yzwl_lixg/project/19.大豆疫霉菌/11.第二次挑选样品/01.gvcf
