cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/GDW012A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/SDW020A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/SDW115A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/SDW144A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/SDW145A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/SDW141A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/SDW142-1A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/SDW139A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/SDW126A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/SDW128A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/SDW129A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/SDW130A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/SDW176A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/SDW175A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/SDW181A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/SDW178A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/GDW120A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/SDW082A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/SDW072A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/SDW057A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/SDW074A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/SDW048A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/SDW095A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/SDW85A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/SDW043A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/SDW089A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/SDW084A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/SDW164A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/SDW192A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/SDW193A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/SDW194A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/SDW152A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/SDW188A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/SDW179A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/SDW162-1A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/SDW023A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/SDW016A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/SDW038A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/GDW111A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/SDW017A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/SDW170A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/SDW171A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/SDW008A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/SDW109A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/SDW116A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/SDW107A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/SDW099A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/SDW097-1A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/SDW097-2A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/SDW022A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/SDW114A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/SDW110A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/SDW111A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/SDW003A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/SDW034A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/SDW096A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/SDW054A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/SDW056A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/SDW053A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/SDW055A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/SDW007A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/SDW030A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/SDW018A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/SDW032A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/SDW031A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/SDW25A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/SDW019A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/SDW26A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/GDW105A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/SDW062A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/WJ98A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/GDW65A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/GDW069-1A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/GDW69-2A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/GDW44-2A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/GDW089A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/GDW98A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/GDW004A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/GDW061A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/GDW95A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/GDW018A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/GDW47A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/GDW68A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/GDW007A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/GDW008A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/GDW040A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/GDW21A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/GDW011A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/GDW055A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/GDW075A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/GDW078A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/SDW125A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/SDW155A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/SDW160A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/SDW190A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/GDW048A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/GDW022A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/GDW052A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/GDW049A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/GDW41A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/GDW030A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/GDW13A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/SDW121A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/SDW120A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/GDW27A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/GDW074A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/GDW38A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/GDW020A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/GDW032A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/GDW023A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/GDW057A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/GDW067A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/GDW31A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/GDW91A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/WK027A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/WJ65A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/WJ23A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/WJ5A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/WJ44A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/WJ31A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/WJ28A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/SDW064A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/WJ9A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/WJ110A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/WJ11-1A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/WJ32A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/WJ36A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/WJ84A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/WJ19A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/WJ88A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/WJ33A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/WJ78A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/WJ56A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/WJ92-2A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/WJ46A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/WJ66A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/WJ100A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/WJ52A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/WJ49A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/WJ58A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/WK085-1A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/WK018A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/WK38A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/WK002A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/WK003A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/WK42A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/WJ45A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/WK057A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/WK084-2A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/WK084-1A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/SDW073-2A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/GDW87A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/DB65A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/DB103A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/DB45A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/DB27A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/DB61A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/DB95A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/DB97A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/DB41A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/DB40A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/DB104A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/DB93A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/DB107A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/DB30A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/WJ51A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/DB57A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/DB67A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/DB75A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/DB79A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/DB76A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/DB68A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/DB74A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/DB72A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/DB22A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/DB53A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/DB63A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/DB106A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/DB102A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/DB89A* ./
cp /share/org/YZWL/yzwl_lixg/project/21.野生大豆群体/01.data/clean/lab/DB8A* ./
