"""HiCPro热图分析流程|HiCPro heatmap analysis pipeline (HiCPro + PlotHiC)"""

import os
import subprocess
import logging
from pathlib import Path
from typing import Optional
import shutil

from .utils import build_conda_command


class HiCProPipeline:
    """HiCPro热图分析流程类|HiCPro heatmap analysis pipeline class (HiCPro + PlotHiC)"""

    def __init__(self, config, logger=None):
        """初始化流程|Initialize pipeline

        Args:
            config: HiCProConfig配置对象|HiCProConfig object
            logger: 日志器|Logger
        """
        self.config = config
        self.logger = logger or logging.getLogger(__name__)

    def run(self):
        """运行完整流程|Run complete pipeline

        Returns:
            bool: 是否成功|Whether successful
        """
        try:
            self.logger.info("=" * 60)
            self.logger.info("开始Hi-C热图分析流程 (HiCPro + PlotHiC)|Starting Hi-C heatmap analysis pipeline (HiCPro + PlotHiC)")
            self.logger.info("=" * 60)

            # 步骤1：准备HiCPro配置|Step 1: Prepare HiCPro config
            if not self._prepare_hicpro_config():
                return False

            # 步骤2：运行HiCPro|Step 2: Run HiCPro
            if not self._run_hicpro():
                return False

            # 步骤3：绘制热图|Step 3: Plot heatmap
            if not self._plot_heatmap():
                return False

            self.logger.info("=" * 60)
            self.logger.info("流程完成|Pipeline completed successfully")
            self.logger.info("=" * 60)
            return True

        except Exception as e:
            self.logger.error(f"流程异常|Pipeline error: {e}")
            import traceback
            traceback.print_exc()
            return False

    def _prepare_hicpro_config(self):
        """准备HiCPro配置文件|Prepare HiCPro configuration file

        Returns:
            bool: 是否成功|Whether successful
        """
        try:
            self.logger.info("步骤1: 准备HiCPro配置文件|Step 1: Preparing HiCPro configuration")

            # 生成染色体大小文件|Generate chromosome sizes file
            chrom_sizes_file = self._generate_chrom_sizes()
            if not chrom_sizes_file:
                return False

            # 生成酶切位点文件|Generate restriction sites file
            res_frag_file = self._generate_resfrag()
            if not res_frag_file:
                self.logger.warning("无法生成酶切位点文件，将不使用限制性片段信息|Cannot generate restriction sites, will not use restriction fragment info")

            # 写入HiCPro配置文件|Write HiCPro config file
            with open(self.config.config_file, 'w') as f:
                f.write(f"# HiCPro configuration file - Auto-generated by biopytools\n\n")

                # 路径和设置|Paths and settings
                f.write(f"TMP_DIR = tmp\n")
                f.write(f"LOGS_DIR = logs\n")
                f.write(f"BOWTIE2_OUTPUT_DIR = bowtie_results\n")
                f.write(f"MAPC_OUTPUT = hic_results\n")
                f.write(f"RAW_DIR = rawdata\n\n")

                # 系统设置|System settings
                f.write(f"N_CPU = {self.config.threads}\n")
                # 注意：HiC-Pro的SORT_RAM单位是MB，不是bytes！
                # Note: HiC-Pro SORT_RAM unit is MB, not bytes!
                # max_memory_gb转换为MB|Convert max_memory_gb to MB
                sort_ram_mb = self.config.max_memory_gb * 1024
                per_thread_mb = sort_ram_mb // self.config.threads
                f.write(f"SORT_RAM = {sort_ram_mb}\n")  # {sort_ram_mb}MB = {self.config.max_memory_gb}GB (每线程约{per_thread_mb}MB|~{per_thread_mb}MB per thread with {self.config.threads} threads)
                f.write(f"LOGFILE = hicpro.log\n\n")

                # 数据设置|Data settings
                f.write(f"PAIR1_EXT = _R1\n")
                f.write(f"PAIR2_EXT = _R2\n\n")

                # 比对选项|Alignment options
                f.write(f"MIN_MAPQ = 10\n")
                # HiC-Pro使用: BOWTIE2_IDX=${BOWTIE2_IDX_PATH}/${REFERENCE_GENOME}|HiC-Pro uses: BOWTIE2_IDX=${BOWTIE2_IDX_PATH}/${REFERENCE_GENOME}
                # 所以BOWTIE2_IDX_PATH是bowtie2索引所在的目录|So BOWTIE2_IDX_PATH is the directory containing bowtie2 index
                # 使用绝对路径避免路径问题|Use absolute path to avoid path issues
                bowtie2_idx_dir = Path(self.config.bowtie2_idx).parent.resolve()
                f.write(f"BOWTIE2_IDX_PATH = {bowtie2_idx_dir}\n")
                f.write(f"BOWTIE2_GLOBAL_OPTIONS = --very-sensitive -L 30 --score-min L,-0.6,-0.2 --end-to-end --reorder\n")
                f.write(f"BOWTIE2_LOCAL_OPTIONS = --very-sensitive -L 20 --score-min L,-0.6,-0.2 --end-to-end --reorder\n\n")

                # 注释文件|Annotation files
                f.write(f"REFERENCE_GENOME = {self.config.genome_id}\n")
                # 使用绝对路径|Use absolute paths
                f.write(f"GENOME_SIZE = {Path(chrom_sizes_file).resolve()}\n\n")

                # 酶切信息|Digestion info
                if res_frag_file:
                    f.write(f"GENOME_FRAGMENT = {Path(res_frag_file).resolve()}\n")
                    f.write(f"LIGATION_SITE = AAGCTAGCTT\n")  # MboI
                f.write(f"MIN_FRAG_SIZE = \n")
                f.write(f"MAX_FRAG_SIZE = \n")
                f.write(f"MIN_INSERT_SIZE = \n")
                f.write(f"MAX_INSERT_SIZE = \n\n")

                # Hi-C处理|Hi-C processing
                f.write(f"MIN_CIS_DIST = \n")
                f.write(f"GET_ALL_INTERACTION_CLASSES = 1\n")
                f.write(f"GET_PROCESS_SAM = 0\n")
                f.write(f"RM_SINGLETON = 1\n")
                f.write(f"RM_MULTI = 1\n")
                f.write(f"RM_DUP = 1\n\n")

                # Contact maps|Contact maps
                f.write(f"BIN_SIZE = {self.config.bin_sizes}\n")
                f.write(f"MATRIX_FORMAT = {self.config.matrix_format}\n\n")

                # 归一化|Normalization
                f.write(f"MAX_ITER = 100\n")
                f.write(f"FILTER_LOW_COUNT_PERC = 0.02\n")
                f.write(f"FILTER_HIGH_COUNT_PERC = 0\n")
                f.write(f"EPS = 0.1\n")

            self.logger.info(f"HiCPro配置文件已生成|HiCPro config created: {self.config.config_file}")
            return True

        except Exception as e:
            self.logger.error(f"准备HiCPro配置失败|Failed to prepare HiCPro config: {e}")
            return False

    def _generate_chrom_sizes(self):
        """生成染色体大小文件|Generate chromosome sizes file

        Returns:
            str: 染色体大小文件路径|Chromosome sizes file path
        """
        try:
            import subprocess

            chrom_sizes_file = self.config.output_path / f"{self.config.genome_id}.chrom.sizes"

            # 检查文件是否存在且非空|Check if file exists and is not empty
            if chrom_sizes_file.exists() and not self.config.force_hicpro:
                if chrom_sizes_file.stat().st_size > 0:
                    self.logger.info(f"染色体大小文件已存在|Chromosome sizes file exists: {chrom_sizes_file}")
                    return str(chrom_sizes_file)
                else:
                    self.logger.warning(f"染色体大小文件为空，将重新生成|Chromosome sizes file is empty, regenerating: {chrom_sizes_file}")

            self.logger.info("生成染色体大小文件|Generating chromosome sizes file")

            # 使用samtools faidx生成.fai索引|Use samtools faidx to generate .fai index
            # 使用conda run wrapper|Use conda run wrapper
            cmd = build_conda_command(
                "samtools",
                ["faidx", self.config.genome]
            )
            self.logger.info(f"命令|Command: {' '.join(cmd)}")

            result = subprocess.run(cmd, capture_output=True, text=True, check=True)

            # samtools faidx创建.fai文件，需要读取.fai文件而不是stdout
            # samtools faidx creates .fai file, need to read .fai file instead of stdout
            fai_file = Path(self.config.genome).parent / (Path(self.config.genome).name + '.fai')

            if not fai_file.exists():
                raise FileNotFoundError(f"samtools faidx未能创建索引文件|faidx index file not found: {fai_file}")

            # 提取染色体大小（从.fai文件）|Extract chromosome sizes (from .fai file)
            with open(fai_file, 'r') as f_in, open(chrom_sizes_file, 'w') as f_out:
                for line in f_in:
                    line = line.strip()
                    if line and not line.startswith('@'):
                        fields = line.split('\t')
                        if len(fields) >= 2:
                            # .fai格式: name, length, offset, linebases, linewidth
                            # 只需要name和length
                            f_out.write(f"{fields[0]}\t{fields[1]}\n")

            self.logger.info(f"染色体大小文件已生成|Chromosome sizes file created: {chrom_sizes_file}")
            return str(chrom_sizes_file)

        except Exception as e:
            self.logger.error(f"生成染色体大小文件失败|Failed to generate chromosome sizes: {e}")
            return None

    def _generate_resfrag(self):
        """生成酶切位点文件|Generate restriction fragment file

        Returns:
            str: 酶切位点文件路径|Restriction fragment file path, or None
        """
        try:
            from Bio import SeqIO
            import re

            res_frag_file = self.config.output_path / f"{self.config.genome_id}_{self.config.restriction_enzyme}_resfrag.bed"

            # 检查文件是否存在且非空|Check if file exists and is not empty
            if res_frag_file.exists() and not self.config.force_hicpro:
                if res_frag_file.stat().st_size > 0:
                    self.logger.info(f"酶切位点文件已存在|Restriction fragment file exists: {res_frag_file}")
                    return str(res_frag_file)
                else:
                    self.logger.warning(f"酶切位点文件为空，将重新生成|Restriction fragment file is empty, regenerating: {res_frag_file}")

            self.logger.info(f"生成{self.config.restriction_enzyme}酶切位点文件|Generating {self.config.restriction_enzyme} restriction fragments")

            # 酶切位点序列|Restriction site sequences
            enzyme_sites = {
                'MboI': 'GATC',
                'HindIII': 'AAGCTT',
                'NcoI': 'CCATGG',
                'EcoRI': 'GAATTC',
                'BamHI': 'GGATCC'
            }

            if self.config.restriction_enzyme not in enzyme_sites:
                self.logger.warning(f"不支持的限制性内切酶|Unsupported restriction enzyme: {self.config.restriction_enzyme}")
                return None

            site_sequence = enzyme_sites[self.config.restriction_enzyme]

            # 生成酶切片段|Generate restriction fragments
            with open(res_frag_file, 'w') as f_out:
                for chrom in SeqIO.parse(self.config.genome, "fasta"):
                    chrom_name = chrom.id
                    seq = str(chrom.seq)

                    # 找到所有酶切位点|Find all restriction sites
                    sites = []
                    pos = 0
                    while True:
                        pos = seq.find(site_sequence, pos)
                        if pos == -1:
                            break
                        sites.append(pos)
                        pos += 1

                    # 生成BED格式的片段|Generate BED format fragments
                    for i in range(len(sites) + 1):
                        start = sites[i - 1] if i > 0 else 0
                        end = sites[i] if i < len(sites) else len(seq)

                        frag_name = f"{chrom_name}_frag_{i + 1}"
                        f_out.write(f"{chrom_name}\t{start}\t{end}\t{frag_name}\t{end - start}\t+\n")

            self.logger.info(f"酶切位点文件已生成|Restriction fragment file created: {res_frag_file}")
            return str(res_frag_file)

        except Exception as e:
            self.logger.error(f"生成酶切位点文件失败|Failed to generate restriction fragments: {e}")
            return None

    def _validate_hicpro_output(self, matrix_dir):
        """验证HiC-Pro输出是否有效|Validate HiC-Pro output is valid

        检查matrix文件是否存在且非空|Check if matrix files exist and are not empty

        Args:
            matrix_dir: Matrix目录路径|Matrix directory path

        Returns:
            bool: 输出是否有效|Whether output is valid
        """
        try:
            # 提取样本名|Extract sample name
            r1_name = Path(self.config.fastq_r1).stem  # 去掉.gz|Remove .gz
            if r1_name.endswith('.fastq') or r1_name.endswith('.fq'):
                r1_name = Path(r1_name).stem  # 再去掉.fastq或.fq|Remove .fastq or .fq
            sample_name = (r1_name
                          .replace('_R1', '').replace('_R2', '')
                          .replace('_1', '').replace('_2', '')
                          .replace('.clean', ''))

            # 检查是否有raw matrix文件|Check if raw matrix files exist
            raw_dir = matrix_dir / sample_name / "raw"
            if not raw_dir.exists():
                return False

            # 检查至少一个resolution的matrix文件且非空|Check at least one resolution's matrix file exists and is not empty
            for resolution_dir in raw_dir.iterdir():
                if resolution_dir.is_dir():
                    matrix_file = resolution_dir / f"{sample_name}_{resolution_dir.name}.matrix"
                    if matrix_file.exists() and matrix_file.stat().st_size > 0:
                        # 找到至少一个有效的matrix文件|Found at least one valid matrix file
                        return True

            # 所有matrix文件都不存在或为空|All matrix files are missing or empty
            return False

        except Exception as e:
            self.logger.warning(f"验证HiC-Pro输出时出错|Error validating HiC-Pro output: {e}")
            return False

    def _run_hicpro(self):
        """运行HiCPro|Run HiCPro

        Returns:
            bool: 是否成功|Whether successful
        """
        try:
            self.logger.info("步骤2: 运行HiCPro|Step 2: Running HiCPro")

            # 检查是否已完成|Check if already done
            matrix_dir = self.config.hicpro_output_dir / "hic_results" / "matrix"
            if matrix_dir.exists() and not self.config.force_hicpro:
                # 验证matrix文件是否有效（非空）|Verify matrix files are valid (not empty)
                matrix_valid = self._validate_hicpro_output(matrix_dir)
                if matrix_valid:
                    self.logger.info("HiCPro输出已存在且有效|HiCPro output exists and valid, skipping")
                    return True
                else:
                    self.logger.warning("HiCPro输出存在但无效（matrix文件为空），将重新运行|HiCPro output exists but invalid (empty matrix files), rerunning")

            # 准备输入数据|Prepare input data
            # HiC-Pro期望输入目录结构: input_dir/sample_name/sample_R1.fastq.gz|HiC-Pro expects: input_dir/sample_name/sample_R1.fastq.gz
            # 我们在output外创建临时输入目录，避免与输出冲突|Create temp input dir outside output to avoid conflicts

            # 提取样本名|Extract sample name from fastq filename
            # 例如: eca_hic_1.clean.fq.gz -> eca_hic|e.g. eca_hic_1.clean.fq.gz -> eca_hic
            r1_name = Path(self.config.fastq_r1).stem  # 去掉.gz|Remove .gz
            if r1_name.endswith('.fastq') or r1_name.endswith('.fq'):
                r1_name = Path(r1_name).stem  # 再去掉.fastq或.fq|Remove .fastq or .fq

            # 移除Read标记|Remove read markers
            base_name = (r1_name
                        .replace('_R1', '').replace('_R2', '')
                        .replace('_1', '').replace('_2', '')
                        .replace('.clean', ''))  # 处理.clean.fq|Handle .clean.fq

            # 创建临时输入目录|Create temporary input directory
            temp_input_dir = self.config.output_path / "hicpro_input"
            if temp_input_dir.exists():
                shutil.rmtree(temp_input_dir)
            temp_input_dir.mkdir(parents=True, exist_ok=True)

            # 创建样本子目录|Create sample subdirectory
            sample_dir = temp_input_dir / base_name
            sample_dir.mkdir(parents=True, exist_ok=True)

            # 复制FASTQ文件到样本目录|Copy FASTQ files to sample directory
            r1_target = sample_dir / f"{base_name}_R1.fastq.gz"
            r2_target = sample_dir / f"{base_name}_R2.fastq.gz"

            self.logger.info(f"复制FASTQ文件|Copying FASTQ files to {sample_dir}")
            shutil.copy2(self.config.fastq_r1, r1_target)
            shutil.copy2(self.config.fastq_r2, r2_target)
            self.logger.info(f"FASTQ文件已复制|FASTQ files copied: {r1_target.name}, {r2_target.name}")

            # HiC-Pro会在输出目录创建自己的rawdata目录|HiC-Pro will create its own rawdata in output
            # 所以我们使用temp_input_dir作为输入，hicpro_output_dir作为输出|So we use temp_input_dir as input, hicpro_output_dir as output

            # 准备bowtie2索引|Prepare bowtie2 index
            # HiC-Pro期望索引名为${BOWTIE2_IDX_PATH}/${REFERENCE_GENOME}|HiC-Pro expects index named ${BOWTIE2_IDX_PATH}/${REFERENCE_GENOME}
            bowtie2_idx_name = Path(self.config.bowtie2_idx).name
            target_idx = self.config.output_path / self.config.genome_id

            # 检查是否有有效的bowtie2索引|Check if valid bowtie2 index exists
            # 只检查bowtie2索引文件（.bt2），不检查bowtie1（.bwt）|Only check bowtie2 (.bt2), not bowtie1 (.bwt)
            has_bowtie2_index = (Path(str(self.config.bowtie2_idx) + '.1.bt2')).exists()

            if not has_bowtie2_index:
                # 没有bowtie2索引，需要构建|No bowtie2 index, need to build
                self.logger.info(f"未找到bowtie2索引，开始构建|No bowtie2 index found, building...")

                bowtie2_build = os.path.expanduser("~/miniforge3/envs/HiC-Pro_v3.1.0/bin/bowtie2-build")

                cmd = build_conda_command(
                    bowtie2_build,
                    ["--threads", str(self.config.threads),
                     self.config.genome, str(target_idx)]
                )

                self._log_command(cmd, "bowtie2-build")
                self.logger.info("构建bowtie2索引中|Building bowtie2 index...")

                result = subprocess.run(
                    cmd,
                    capture_output=True,
                    text=True,
                    timeout=7200  # 2小时超时
                )

                if result.returncode != 0:
                    self.logger.error(f"bowtie2索引构建失败|bowtie2-build failed: {result.stderr}")
                    return False

                self.logger.info(f"bowtie2索引构建完成|Bowtie2 index built: {target_idx}")

                # 更新bowtie2_idx路径|Update bowtie2_idx path
                self.config.bowtie2_idx = str(target_idx)

                # 索引路径已更改，重新生成配置文件|Index path changed, regenerate config file
                self.logger.info("重新生成HiCPro配置文件|Regenerating HiCPro config with new index path")
                self._prepare_hicpro_config()
            else:
                # 有bowtie2索引，检查文件名是否匹配|Has bowtie2 index, check if name matches
                if bowtie2_idx_name != self.config.genome_id and bowtie2_idx_name != f"{self.config.genome_id}.fa":
                    # 在工作目录复制索引文件|Copy index files to working directory
                    extensions = ['.1.bt2', '.2.bt2', '.3.bt2', '.4.bt2', '.rev.1.bt2', '.rev.2.bt2']

                    copied = False
                    for ext in extensions:
                        src = Path(str(self.config.bowtie2_idx) + ext)
                        if src.exists():
                            dst = Path(str(target_idx) + ext)
                            # 如果目标已存在且不是源文件，删除|Remove if exists and not the source
                            if dst.exists() and dst.resolve() != src.resolve():
                                dst.unlink()
                            # 复制文件（如果不存在）|Copy file if not exists
                            if not dst.exists():
                                shutil.copy2(src, dst)
                                copied = True

                    if copied:
                        self.logger.info(f"复制bowtie2索引文件|Copied bowtie2 index files: {target_idx}")
                    # 更新bowtie2_idx路径|Update bowtie2_idx path
                    self.config.bowtie2_idx = str(target_idx)

            # 选择运行方式：直接运行或singularity|Choose run mode: direct or singularity
            if self.config.use_singularity:
                self.logger.info("使用Singularity运行HiCPro|Using Singularity to run HiCPro")
                cmd = [
                    self.config.singularity_exec, "exec",
                    "--bind", f"{self.config.output_path}:/data",
                    "--bind", f"{Path(self.config.genome).parent}:/genome",
                    str(self.config.hicpro_sif),
                    "HiC-Pro",
                    "-c", f"/data/{Path(self.config.config_file).name}",
                    "-i", "/data/rawdata",
                    "-o", "/data/hicpro_output"
                ]
            else:
                self.logger.info("直接运行HiCPro|Running HiC-Pro directly")

                cmd = ['conda', 'run', '-n', 'HiC-Pro_v3.1.0', '--no-capture-output',
                       self.config.hicpro_path,
                       "-c", self.config.config_file,
                       "-i", str(temp_input_dir),
                       "-o", str(self.config.hicpro_output_dir)]

            self._log_command(cmd, "HiCPro")
            self.logger.info("运行HiCPro中|Running HiCPro...")

            result = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                timeout=72000  # 20小时超时
            )

            if result.returncode != 0:
                self.logger.error(f"HiCPro运行失败|HiCPro failed: {result.stderr}")
                return False

            self.logger.info("HiCPro运行成功|HiCPro completed successfully")
            return True

        except subprocess.TimeoutExpired:
            self.logger.error("HiCPro运行超时|HiCPro timeout")
            return False
        except Exception as e:
            self.logger.error(f"运行HiCPro异常|HiCPro error: {e}")
            import traceback
            traceback.print_exc()
            return False

    def _plot_heatmap(self):
        """绘制热图|Plot heatmap

        Returns:
            bool: 是否成功|Whether successful
        """
        try:
            self.logger.info("步骤3: 绘制热图|Step 3: Plotting heatmap")

            # 检查是否已完成|Check if already done
            if self.config.skip_existing and self.config.heatmap_file.exists():
                if self.config.heatmap_file.stat().st_size > 0:
                    self.logger.info(f"跳过|Skipping: 热图已存在|Heatmap exists: {self.config.heatmap_file}")
                    return True

            # 查找matrix文件|Find matrix files
            matrix_dir = self.config.hicpro_output_dir / "hic_results" / "matrix"

            # 提取样本名|Extract sample name
            r1_name = Path(self.config.fastq_r1).stem  # 去掉.gz|Remove .gz
            if r1_name.endswith('.fastq') or r1_name.endswith('.fq'):
                r1_name = Path(r1_name).stem  # 再去掉.fastq或.fq|Remove .fastq or .fq
            sample_name = (r1_name
                          .replace('_R1', '').replace('_R2', '')
                          .replace('_1', '').replace('_2', '')
                          .replace('.clean', ''))

            # 选择最接近的分辨率|Select closest resolution
            available_bins = []
            for bin_size_str in self.config.bin_sizes.split():
                try:
                    bin_size = int(bin_size_str)
                    # HiC-Pro的文件名格式：{sample}_{bin_size}_iced.matrix
                    # HiC-Pro filename format: sample_bin_size_iced.matrix
                    matrix_file = matrix_dir / sample_name / "iced" / bin_size_str / f"{sample_name}_{bin_size}_iced.matrix"
                    bed_file = matrix_dir / sample_name / "raw" / bin_size_str / f"{sample_name}_{bin_size}_abs.bed"

                    if matrix_file.exists() and bed_file.exists():
                        available_bins.append((bin_size, matrix_file, bed_file))
                except ValueError:
                    continue

            if not available_bins:
                self.logger.error("未找到可用的matrix文件|No valid matrix files found")
                return False

            # 选择最接近的分辨率|Select closest resolution
            closest = min(available_bins, key=lambda x: abs(x[0] - self.config.resolution))
            bin_size, matrix_file, bed_file = closest

            self.logger.info(f"使用分辨率|Using resolution: {bin_size}bp (target: {self.config.resolution}bp)")
            self.logger.info(f"Matrix文件|Matrix file: {matrix_file}")
            self.logger.info(f"BED文件|BED file: {bed_file}")

            # 构建plothic命令|Build plothic command
            # 使用conda run wrapper|Use conda run wrapper
            cmd = build_conda_command(
                self.config.plothic_path,
                [
                    "-matrix", str(matrix_file),
                    "--abs-bed", str(bed_file),
                    "-o", str(self.config.plot_dir),
                    "-format", self.config.output_format,
                    "-cmap", self.config.color_map,
                    "-dpi", str(self.config.dpi),
                    "-g", self.config.genome_id,
                    "-log",  # 对数变换|Log transform
                    "--bar-max", str(self.config.bar_max),  # 设置颜色条最大值|Set color bar max value
                ]
            )

            self._log_command(cmd, "plothic")
            self.logger.info("绘制热图中|Plotting heatmap...")

            result = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                timeout=1800  # 30分钟超时
            )

            if result.returncode != 0:
                self.logger.error(f"plothic失败|plothic failed: {result.stderr}")
                return False

            # 查找生成的文件|Find generated file
            import glob
            # plothic可能生成的文件名格式|Possible plothic output filenames:
            # 1. {genome_id}_*.{format} (例如 OV53_*.pdf)
            # 2. GenomeContact.{format} (默认文件名)
            patterns = [
                str(self.config.plot_dir / f"{self.config.genome_id}_*.{self.config.output_format}"),
                str(self.config.plot_dir / f"GenomeContact.{self.config.output_format}"),
                str(self.config.plot_dir / f"*.{self.config.output_format}")
            ]

            generated_files = []
            for pattern in patterns:
                files = glob.glob(pattern)
                if files:
                    generated_files = files
                    break

            if generated_files:
                # 重命名到目标文件|Rename to target file
                generated_file = Path(generated_files[0])
                if generated_file != self.config.heatmap_file:
                    shutil.move(str(generated_file), str(self.config.heatmap_file))
                    self.logger.info(f"重命名|Renamed: {generated_file} -> {self.config.heatmap_file}")
            else:
                self.logger.warning(f"未找到生成的热图文件|Generated heatmap file not found, searched patterns: {patterns}")

            self.logger.info(f"热图已生成|Heatmap created: {self.config.heatmap_file}")
            return True

        except subprocess.TimeoutExpired:
            self.logger.error("绘制热图超时|Plotting timeout")
            return False
        except Exception as e:
            self.logger.error(f"绘制热图异常|Plotting error: {e}")
            import traceback
            traceback.print_exc()
            return False

    def _log_command(self, cmd_list, description=""):
        """记录执行的命令|Log executed command

        Args:
            cmd_list: 命令列表|Command list
            description: 命令描述|Command description
        """
        if isinstance(cmd_list, list):
            cmd_str = ' '.join(
                f'"{arg}"' if ' ' in str(arg) else str(arg)
                for arg in cmd_list
            )
        else:
            cmd_str = str(cmd_list)

        if description:
            self.logger.info(f"{description}命令|{description} command:")
        self.logger.info(f"  {cmd_str}")
