#!/bin/bash
# =============================================================
# 删除超算上模块未引用的旧 conda 环境|Delete module-unused legacy envs
# 清单来源|Lists: scripts/delete_list.txt (155个) / scripts/protect_list.txt (73个)
#   由 scripts/analyze_full_deletion.py 生成|generated by the analyzer
#
# 删除前提|PREREQUISITES:
#   1. 新代码已同步到超算(github 拉取)且模块跑通验证
#   2. 确认清单: cat scripts/delete_list.txt
#
# 安全设计|Safety:
#   - 默认 DRY-RUN, 只列不删|dry-run by default
#   - 只删 delete_list.txt 里的环境|only removes envs in delete_list.txt
#   - protect_list.txt 为防呆名单, 冲突即中止|abort on any overlap
#   - 删除前逐个确认存在性并显示大小|checks existence and size
#
# 用法|Usage:
#   bash scripts/delete_obsolete_envs.sh              # dry-run 预览
#   bash scripts/delete_obsolete_envs.sh --delete     # 真正删除(需输入 yes)
# =============================================================
set -u

CONDA="${CONDA:-/share/org/YZWL/yzwl_lixg/miniforge3/bin/conda}"
ENVS_DIR="${ENVS_DIR:-/share/org/YZWL/yzwl_lixg/miniforge3/envs}"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
DELETE_FILE="$SCRIPT_DIR/delete_list.txt"
PROTECT_FILE="$SCRIPT_DIR/protect_list.txt"
DO_DELETE=0
if [ "${1:-}" = "--delete" ]; then DO_DELETE=1; fi

echo "==== 前置检查|Preflight ===="
echo "conda: $CONDA"
echo "envs目录|envs dir: $ENVS_DIR"
echo "删除清单|delete list: $DELETE_FILE"
echo "保护清单|protect list: $PROTECT_FILE"
[ -x "$CONDA" ] || { echo "错误|Error: conda 不存在: $CONDA"; exit 1; }
[ -d "$ENVS_DIR" ] || { echo "错误|Error: envs 目录不存在"; exit 1; }
[ -f "$DELETE_FILE" ] || { echo "错误|Error: 删除清单不存在"; exit 1; }
[ -f "$PROTECT_FILE" ] || { echo "错误|Error: 保护清单不存在"; exit 1; }
if [ "$DO_DELETE" = "0" ]; then
  echo "模式|Mode: DRY-RUN (加 --delete 才真正删除)"
else
  echo "模式|Mode: DELETE !!"
fi

# 读清单|Load lists (bash3.2 兼容|compatible)
DELETE_LIST=()
while IFS= read -r line; do DELETE_LIST+=("$line"); done < "$DELETE_FILE"
PROTECT_LIST=()
while IFS= read -r line; do PROTECT_LIST+=("$line"); done < "$PROTECT_FILE"
echo "删除清单条目|delete entries: ${#DELETE_LIST[@]} | 保护清单条目|protect entries: ${#PROTECT_LIST[@]}"

echo "==== 清单自检|List self-check ===="
BAD=0
for e in "${DELETE_LIST[@]}"; do
  for p in "${PROTECT_LIST[@]}"; do
    if [ "$e" = "$p" ]; then
      echo "错误|Conflict: $e 同时在删除和保护清单"; BAD=1
    fi
  done
done
[ "$BAD" = "1" ] && { echo "自检失败, 中止|Abort"; exit 1; }
echo "通过|OK: 两清单无冲突"

echo ""
echo "==== 扫描|Scanning ===="
TO_DELETE=()
for e in "${DELETE_LIST[@]}"; do
  [ -z "$e" ] && continue
  d="$ENVS_DIR/$e"
  if [ -d "$d" ]; then
    size=$(du -sh "$d" 2>/dev/null | cut -f1)
    echo "  [存在|exists] $e ($size)"
    TO_DELETE+=("$e")
  else
    echo "  [不存在, 跳过|missing] $e"
  fi
done

echo ""
echo "==== 计划|Plan ===="
echo "  待删除|To delete: ${#TO_DELETE[@]} 个"

if [ "$DO_DELETE" = "0" ]; then
  echo "DRY-RUN 结束|Done. 未删除任何环境|Nothing deleted."
  echo "确认无误后执行|To execute: bash scripts/delete_obsolete_envs.sh --delete"
  exit 0
fi

read -r -p "警告|WARNING: 确认删除以上 ${#TO_DELETE[@]} 个环境? 输入 yes 继续: " ANS
if [ "$ANS" != "yes" ]; then echo "已取消|Cancelled"; exit 0; fi

echo ""
FAIL=0
for e in "${TO_DELETE[@]}"; do
  echo "  删除|Removing: $e"
  if "$CONDA" env remove -p "$ENVS_DIR/$e" -y >/dev/null 2>&1; then
    echo "    已删除|Removed: $e"
  else
    echo "    失败|Failed: $e"; FAIL=1
  fi
done
echo ""
echo "完成|Done. 失败|Failed: $FAIL"
